orm_site_prj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_app.urls')),
]

site_app/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'site_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.first_page),
    path('page/<int:pk>', views.page, name='page'),
 ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

site_app/models.py
from django.db import models
from django.urls import reverse

class Item(models.Model):

    item_title = models.CharField(verbose_name = 'Заголовок (title)', max_length=255, default="Заголовок" )

    item_nav = models.CharField(verbose_name = 'Название ссылки', max_length=255, default="Название ссылки")

    item_nav_position = models.IntegerField(verbose_name = 'Приоритет ссылки в навигации (0 - исключить)', default=1, help_text="большее - число правее, 0 - исключить из навигации")

    item_content = models.TextField(verbose_name = 'Основное содержание страницы', 
    default = '<a id="top_of _page" href="#h1" class="card-link">На раздел 1</a>   <h6 class="card-subtitle mb-2 text-body-secondary ">   <a id="h1">Раздел 1</a></h6>   <p class="card-text">Содержание раздела 1</p>   <img src="/static/images/settings_django.png"  height="30px">    <a href="#top_of _page" class="card-link">к началу страницы</a>')
    
    item_current_date = models.DateTimeField(verbose_name = "Дата Записи", auto_now=True)

    class Meta:
        verbose_name = 'Содержание текущей страницы'
        verbose_name_plural = 'Содержание всех страниц'
        ordering = ('-item_nav_position',)

    def __str__(self):
        return f"pk: {self.pk};  item_title: {self.item_title}"

site_app/views.py
from django.shortcuts import render, redirect
from . models import Item

def first_page(request):
    # return redirect('page/1')
    return render(request, 'index.html')

def page(request, pk):
    nav_objects = Item.objects.values('id','item_nav', 'item_nav_position').filter(item_nav_position__gt=0).order_by('-item_nav_position')
    print("nav_objects: ", nav_objects)
    content_object = Item.objects.values().get(id=pk)
    print("content_object:\n", content_object)
    context = {'pk': pk, 'nav_objects': nav_objects, 'content_object': content_object}
    return render(request, 'page.html', context)

site_app/templates/index.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Начинаем</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/mycss.css" rel="stylesheet">
</head>

<body>
<div class="container">

    <header class="gryffindor" style="margin-bottom: 30px; padding: 40px; border-radius: 15px;">
        <h1 style="padding: 10px 20px; border-radius: 15px;">
            Добро пожаловать в Hogwarts!
        </h1>
    </header>

    <div class="card bg-transparent border-0">


        <div class="card-body">
            <h2>Начинаем</h2>
            <p>
                Панель администратора:<br>
                <code>http://127.0.0.1:8000/admin</code> — логин: <b>root</b>, пароль: <b>root</b><br><br>
                Открыть сайт:<br>
                <code>http://127.0.0.1:8000/page/1</code>
            </p>
        </div>
    </div>

    <div class="card bg-transparent border-0 mt-4">
        <div class="card-body">
            <p>
                Мир Волшебства и магии!
            </p>
        </div>
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

site_app/templates/layout.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>{% block title %}Моё обучение в Вышке{% endblock %}</title>

    {% load static %}
    <link href="{% static 'css/site_2.css' %}" rel="stylesheet">
</head>

<body>
<div class="container">

    <header class="gryffindor" style="padding: 30px; border-radius: 15px; margin-bottom: 30px;">
        <div class="intro">
            <h1 class="main-title" style="text-shadow: 2px 2px 4px rgb(67, 82, 83);">
                Я и моё обучение в Вышке
            </h1>
        </div>
    </header>

    <main class="fade-in" style="margin-top: 50px;">
        <div class="content-body" style="background: rgba(0, 0, 0, 0.6); padding: 20px; border-radius: 15px;">
            {% block content %}{% endblock %}
        </div>
    </main>

    <footer class="footer-card" style="margin-top: 50px;">
        <div class="footer-body" style="background: rgba(0, 0, 0, 0.6); padding: 15px; border-radius: 10px;">
            <p>Высшая школа экономики</p>
        </div>
    </footer>

</div>
</body>
</html>

site_app/templates/page.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    <title>{{ content_object.item_title }}</title>
{% endblock %}

{% block content %}
    <div class="fade-in" style="margin-top: 50px;">

        <nav class="hogwarts-list mb-4">
            <ul class="nav nav-tabs" style="justify-content: center;">
                {% for object in nav_objects %}
                    <li class="nav-item gryffindor" style="margin: 0 5px;">
                        <a class="nav-link {% if pk == object.id %}active{% endif %}" style="color: white;" 
                           href="{% url 'site_app:page' pk=object.id %}">
                            {{ object.item_nav }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </nav>

        <div style="background: rgba(0, 0, 0, 0.6); padding: 20px; border-radius: 15px;">
            <h2 class="card-title text-center mb-4" style="color: #8b0000; text-shadow: 2px 2px 4px rgb(67, 82, 83);">
                {% autoescape off %}{{ content_object.item_title }}{% endautoescape %}
            </h2>

            <div class="content-text" style="font-size: 20px; line-height: 1.5; color: #dfba4a;">
                {% autoescape off %}
                    {{ content_object.item_content }}
                {% endautoescape %}
            </div>
        </div>

    </div>
{% endblock %}